name: learn-github-actions
on:
  push:
    branches:
      - main # または適切なブランチ名

jobs:
  test-Action:
    # runs-on: ubuntu-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - run: python -m pip install --upgrade pip


      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install someone 
        run: pip install -r .github/requirements.txt

      - name: Run Python
        run: python .github/test.py
      
      - run: snap install drawio
