name: learn-github-actions
on:
  push:
    branches:
      - main # または適切なブランチ名

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: python -m pip install --upgrade pip
      - run: pip install pipenv
      - run: pipenv install -d
      - run: pipenv run pytest -n auto --cov
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"