name: learn-github-actions
on:
  push:
    branches:
      - main # または適切なブランチ名

jobs:
  test-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - run: python -m pip install --upgrade pip

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install someone 
        run: pip install -r requirements.txt

      - name: Run Python
        run: python sample.py